### ISSUE TITLE
Expose eZ repository in migration script

### ISSUE THREAD

**Issue by emodric** [kreait/ezpublish-migrations-bundle#9]
Just being able to create content is somewhat limited. Often it is needed to perform other tasks like adding fields to field types, adding sections and so on.

How about exposing the entire eZ repository for users?

**Comment by jeromegamez** [comment]
Within a Migration, the repository is available through the `repository` property, see https://github.com/kreait/ezpublish-migrations-bundle/blob/master/src/Migrations/EzPublishMigration.php#L35

**Comment by emodric** [comment]
Right! I overlooked that is was protected! Thanks!

**Comment by jeromegamez** [comment]
Happy this could be resolved so quickly :). Nonetheless I have updated the README to make the usage a little bit more visible. Thank you for reaching out!

**Comment by emodric** [comment]
:+1: :)
